name: Deploy Hugo Site to Yandex Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Site
      run: hugo --minify

    - name: Configure AWS CLI for Yandex Cloud
      run: |
        aws configure set aws_access_key_id ${{ secrets.YC_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.YC_SECRET_KEY }}
        aws configure set default.region ru-central1
        aws configure set default.output json

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip"
        unzip awscli.zip
        sudo ./aws/install

    - name: Deploy to Yandex Cloud Object Storage
      run: |
        aws s3 sync ./public s3://rt-agency \
          --endpoint-url=https://storage.yandexcloud.net \
          --delete \
          --cache-control "public, max-age=31536000" \
          --metadata-directive REPLACE

    - name: Set correct Content-Type for HTML files
      run: |
        aws s3 cp s3://rt-agency/ s3://rt-agency/ \
          --endpoint-url=https://storage.yandexcloud.net \
          --recursive \
          --exclude "*" \
          --include "*.html" \
          --content-type="text/html; charset=utf-8" \
          --metadata-directive REPLACE

    - name: Set correct Content-Type for CSS files
      run: |
        aws s3 cp s3://rt-agency/ s3://rt-agency/ \
          --endpoint-url=https://storage.yandexcloud.net \
          --recursive \
          --exclude "*" \
          --include "*.css" \
          --content-type="text/css" \
          --metadata-directive REPLACE

    - name: Set correct Content-Type for JS files
      run: |
        aws s3 cp s3://rt-agency/ s3://rt-agency/ \
          --endpoint-url=https://storage.yandexcloud.net \
          --recursive \
          --exclude "*" \
          --include "*.js" \
          --content-type="application/javascript" \
          --metadata-directive REPLACE

menu:
  main:
    - identifier: main
      name: "Алина Патрик"
      url: "/"
      weight: 1
    # - identifier: about
    #   name: "О нас"
    #   url: "/about/"
    #   weight: 1
    # - identifier: blog
    #   name: "Блог"
    #   url: "/blog/"
    #   weight: 2